//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Band complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Band">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startFrequency" type="{}positive-double"/>
 *         &lt;element name="endFrequency" type="{}positive-double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Band", propOrder = {
    "startFrequency",
    "endFrequency"
})
public class Band {

    protected double startFrequency;
    protected double endFrequency;

    /**
     * Gets the value of the startFrequency property.
     * 
     */
    public double getStartFrequency() {
        return startFrequency;
    }

    /**
     * Sets the value of the startFrequency property.
     * 
     */
    public void setStartFrequency(double value) {
        this.startFrequency = value;
    }

    /**
     * Gets the value of the endFrequency property.
     * 
     */
    public double getEndFrequency() {
        return endFrequency;
    }

    /**
     * Sets the value of the endFrequency property.
     * 
     */
    public void setEndFrequency(double value) {
        this.endFrequency = value;
    }

}
