//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Combinations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Combinations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="multiple" type="{}Multiple" maxOccurs="unbounded"/>
 *           &lt;element name="alternatives" type="{}Alternatives" maxOccurs="unbounded"/>
 *           &lt;element name="competing" type="{}Competing"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Combinations", propOrder = {
    "multiple",
    "alternatives",
    "competing"
})
public class Combinations {

    protected List<Multiple> multiple;
    protected List<Alternatives> alternatives;
    protected Competing competing;

    /**
     * Gets the value of the multiple property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiple property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultiple().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Multiple }
     * 
     * 
     */
    public List<Multiple> getMultiple() {
        if (multiple == null) {
            multiple = new ArrayList<Multiple>();
        }
        return this.multiple;
    }

    /**
     * Gets the value of the alternatives property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternatives property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternatives().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Alternatives }
     * 
     * 
     */
    public List<Alternatives> getAlternatives() {
        if (alternatives == null) {
            alternatives = new ArrayList<Alternatives>();
        }
        return this.alternatives;
    }

    /**
     * Gets the value of the competing property.
     * 
     * @return
     *     possible object is
     *     {@link Competing }
     *     
     */
    public Competing getCompeting() {
        return competing;
    }

    /**
     * Sets the value of the competing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Competing }
     *     
     */
    public void setCompeting(Competing value) {
        this.competing = value;
    }

}
