//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Confidence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Confidence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="measure" type="{}zero-one-exclusive-double"/>
 *         &lt;element name="approach" type="{}Approach"/>
 *         &lt;element name="nature" type="{}Nature"/>
 *         &lt;element name="derivation" type="{}Derivation" minOccurs="0"/>
 *         &lt;element name="maxDwellTime" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Confidence", propOrder = {
    "measure",
    "approach",
    "nature",
    "derivation",
    "maxDwellTime"
})
public class Confidence {

    protected double measure;
    @XmlElement(required = true)
    protected Approach approach;
    @XmlElement(required = true)
    protected Nature nature;
    protected Derivation derivation;
    protected Double maxDwellTime;

    /**
     * Gets the value of the measure property.
     * 
     */
    public double getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     * 
     */
    public void setMeasure(double value) {
        this.measure = value;
    }

    /**
     * Gets the value of the approach property.
     * 
     * @return
     *     possible object is
     *     {@link Approach }
     *     
     */
    public Approach getApproach() {
        return approach;
    }

    /**
     * Sets the value of the approach property.
     * 
     * @param value
     *     allowed object is
     *     {@link Approach }
     *     
     */
    public void setApproach(Approach value) {
        this.approach = value;
    }

    /**
     * Gets the value of the nature property.
     * 
     * @return
     *     possible object is
     *     {@link Nature }
     *     
     */
    public Nature getNature() {
        return nature;
    }

    /**
     * Sets the value of the nature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nature }
     *     
     */
    public void setNature(Nature value) {
        this.nature = value;
    }

    /**
     * Gets the value of the derivation property.
     * 
     * @return
     *     possible object is
     *     {@link Derivation }
     *     
     */
    public Derivation getDerivation() {
        return derivation;
    }

    /**
     * Sets the value of the derivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Derivation }
     *     
     */
    public void setDerivation(Derivation value) {
        this.derivation = value;
    }

    /**
     * Gets the value of the maxDwellTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxDwellTime() {
        return maxDwellTime;
    }

    /**
     * Sets the value of the maxDwellTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxDwellTime(Double value) {
        this.maxDwellTime = value;
    }

}
