//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Cycle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Cycle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firstOn" type="{}offset-dateTime"/>
 *         &lt;element name="durationOn" type="{}simple-duration"/>
 *         &lt;element name="durationOff" type="{}simple-duration"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cycle", propOrder = {
    "firstOn",
    "durationOn",
    "durationOff"
})
public class Cycle {

    @XmlElement(required = true)
    protected XMLGregorianCalendar firstOn;
    @XmlElement(required = true)
    protected String durationOn;
    @XmlElement(required = true)
    protected String durationOff;

    /**
     * Gets the value of the firstOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstOn() {
        return firstOn;
    }

    /**
     * Sets the value of the firstOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstOn(XMLGregorianCalendar value) {
        this.firstOn = value;
    }

    /**
     * Gets the value of the durationOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationOn() {
        return durationOn;
    }

    /**
     * Sets the value of the durationOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationOn(String value) {
        this.durationOn = value;
    }

    /**
     * Gets the value of the durationOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationOff() {
        return durationOff;
    }

    /**
     * Sets the value of the durationOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationOff(String value) {
        this.durationOff = value;
    }

}
