//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HoppingData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HoppingData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dwellTime" type="{}positive-double"/>
 *         &lt;element name="revisitPeriod" type="{}positive-double"/>
 *         &lt;choice>
 *           &lt;element name="frequencyList" type="{}FrequencyList"/>
 *           &lt;element name="bandList" type="{}BandList"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HoppingData", propOrder = {
    "dwellTime",
    "revisitPeriod",
    "frequencyList",
    "bandList"
})
public class HoppingData {

    protected double dwellTime;
    protected double revisitPeriod;
    protected FrequencyList frequencyList;
    protected BandList bandList;

    /**
     * Gets the value of the dwellTime property.
     * 
     */
    public double getDwellTime() {
        return dwellTime;
    }

    /**
     * Sets the value of the dwellTime property.
     * 
     */
    public void setDwellTime(double value) {
        this.dwellTime = value;
    }

    /**
     * Gets the value of the revisitPeriod property.
     * 
     */
    public double getRevisitPeriod() {
        return revisitPeriod;
    }

    /**
     * Sets the value of the revisitPeriod property.
     * 
     */
    public void setRevisitPeriod(double value) {
        this.revisitPeriod = value;
    }

    /**
     * Gets the value of the frequencyList property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyList }
     *     
     */
    public FrequencyList getFrequencyList() {
        return frequencyList;
    }

    /**
     * Sets the value of the frequencyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyList }
     *     
     */
    public void setFrequencyList(FrequencyList value) {
        this.frequencyList = value;
    }

    /**
     * Gets the value of the bandList property.
     * 
     * @return
     *     possible object is
     *     {@link BandList }
     *     
     */
    public BandList getBandList() {
        return bandList;
    }

    /**
     * Sets the value of the bandList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BandList }
     *     
     */
    public void setBandList(BandList value) {
        this.bandList = value;
    }

}
