//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HopRated complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HopRated">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hoppingData" type="{}HoppingData"/>
 *         &lt;element name="toleranceThreshold" type="{}zero-one-exclusive-double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HopRated", propOrder = {
    "hoppingData",
    "toleranceThreshold"
})
public class HopRated {

    @XmlElement(required = true)
    protected HoppingData hoppingData;
    protected double toleranceThreshold;

    /**
     * Gets the value of the hoppingData property.
     * 
     * @return
     *     possible object is
     *     {@link HoppingData }
     *     
     */
    public HoppingData getHoppingData() {
        return hoppingData;
    }

    /**
     * Sets the value of the hoppingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoppingData }
     *     
     */
    public void setHoppingData(HoppingData value) {
        this.hoppingData = value;
    }

    /**
     * Gets the value of the toleranceThreshold property.
     * 
     */
    public double getToleranceThreshold() {
        return toleranceThreshold;
    }

    /**
     * Sets the value of the toleranceThreshold property.
     * 
     */
    public void setToleranceThreshold(double value) {
        this.toleranceThreshold = value;
    }

}
