//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntermodulationMask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntermodulationMask">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="intermediateFrequency" type="{}positive-double" minOccurs="0"/>
 *         &lt;element name="highSideInjection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="imCombiningMask" type="{}SCMMask"/>
 *         &lt;element name="imAmplificationMask" type="{}SCMMask" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntermodulationMask", propOrder = {
    "order",
    "intermediateFrequency",
    "highSideInjection",
    "imCombiningMask",
    "imAmplificationMask"
})
public class IntermodulationMask {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger order;
    protected Double intermediateFrequency;
    protected Boolean highSideInjection;
    @XmlElement(required = true)
    protected SCMMask imCombiningMask;
    protected SCMMask imAmplificationMask;

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrder(BigInteger value) {
        this.order = value;
    }

    /**
     * Gets the value of the intermediateFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIntermediateFrequency() {
        return intermediateFrequency;
    }

    /**
     * Sets the value of the intermediateFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIntermediateFrequency(Double value) {
        this.intermediateFrequency = value;
    }

    /**
     * Gets the value of the highSideInjection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHighSideInjection() {
        return highSideInjection;
    }

    /**
     * Sets the value of the highSideInjection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHighSideInjection(Boolean value) {
        this.highSideInjection = value;
    }

    /**
     * Gets the value of the imCombiningMask property.
     * 
     * @return
     *     possible object is
     *     {@link SCMMask }
     *     
     */
    public SCMMask getImCombiningMask() {
        return imCombiningMask;
    }

    /**
     * Sets the value of the imCombiningMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCMMask }
     *     
     */
    public void setImCombiningMask(SCMMask value) {
        this.imCombiningMask = value;
    }

    /**
     * Gets the value of the imAmplificationMask property.
     * 
     * @return
     *     possible object is
     *     {@link SCMMask }
     *     
     */
    public SCMMask getImAmplificationMask() {
        return imAmplificationMask;
    }

    /**
     * Sets the value of the imAmplificationMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCMMask }
     *     
     */
    public void setImAmplificationMask(SCMMask value) {
        this.imAmplificationMask = value;
    }

}
