//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Location complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Location">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="point" type="{}Point"/>
 *           &lt;element name="pointSurface" type="{}PointSurface"/>
 *           &lt;element name="circularSurface" type="{}CircularSurface"/>
 *           &lt;element name="polygonSurface" type="{}PolygonSurface"/>
 *           &lt;element name="surfacePath" type="{}SurfacePath"/>
 *           &lt;element name="cylinder" type="{}Cylinder"/>
 *           &lt;element name="polyhedron" type="{}Polyhedron"/>
 *           &lt;element name="path" type="{}Path"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Location", propOrder = {
    "point",
    "pointSurface",
    "circularSurface",
    "polygonSurface",
    "surfacePath",
    "cylinder",
    "polyhedron",
    "path"
})
public class Location {

    protected Point point;
    protected PointSurface pointSurface;
    protected CircularSurface circularSurface;
    protected PolygonSurface polygonSurface;
    protected SurfacePath surfacePath;
    protected Cylinder cylinder;
    protected Polyhedron polyhedron;
    protected Path path;

    /**
     * Gets the value of the point property.
     * 
     * @return
     *     possible object is
     *     {@link Point }
     *     
     */
    public Point getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link Point }
     *     
     */
    public void setPoint(Point value) {
        this.point = value;
    }

    /**
     * Gets the value of the pointSurface property.
     * 
     * @return
     *     possible object is
     *     {@link PointSurface }
     *     
     */
    public PointSurface getPointSurface() {
        return pointSurface;
    }

    /**
     * Sets the value of the pointSurface property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointSurface }
     *     
     */
    public void setPointSurface(PointSurface value) {
        this.pointSurface = value;
    }

    /**
     * Gets the value of the circularSurface property.
     * 
     * @return
     *     possible object is
     *     {@link CircularSurface }
     *     
     */
    public CircularSurface getCircularSurface() {
        return circularSurface;
    }

    /**
     * Sets the value of the circularSurface property.
     * 
     * @param value
     *     allowed object is
     *     {@link CircularSurface }
     *     
     */
    public void setCircularSurface(CircularSurface value) {
        this.circularSurface = value;
    }

    /**
     * Gets the value of the polygonSurface property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonSurface }
     *     
     */
    public PolygonSurface getPolygonSurface() {
        return polygonSurface;
    }

    /**
     * Sets the value of the polygonSurface property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonSurface }
     *     
     */
    public void setPolygonSurface(PolygonSurface value) {
        this.polygonSurface = value;
    }

    /**
     * Gets the value of the surfacePath property.
     * 
     * @return
     *     possible object is
     *     {@link SurfacePath }
     *     
     */
    public SurfacePath getSurfacePath() {
        return surfacePath;
    }

    /**
     * Sets the value of the surfacePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfacePath }
     *     
     */
    public void setSurfacePath(SurfacePath value) {
        this.surfacePath = value;
    }

    /**
     * Gets the value of the cylinder property.
     * 
     * @return
     *     possible object is
     *     {@link Cylinder }
     *     
     */
    public Cylinder getCylinder() {
        return cylinder;
    }

    /**
     * Sets the value of the cylinder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cylinder }
     *     
     */
    public void setCylinder(Cylinder value) {
        this.cylinder = value;
    }

    /**
     * Gets the value of the polyhedron property.
     * 
     * @return
     *     possible object is
     *     {@link Polyhedron }
     *     
     */
    public Polyhedron getPolyhedron() {
        return polyhedron;
    }

    /**
     * Sets the value of the polyhedron property.
     * 
     * @param value
     *     allowed object is
     *     {@link Polyhedron }
     *     
     */
    public void setPolyhedron(Polyhedron value) {
        this.polyhedron = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link Path }
     *     
     */
    public Path getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link Path }
     *     
     */
    public void setPath(Path value) {
        this.path = value;
    }

}
