//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ieee.dyspansc._1900._5.scm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ieee.dyspansc._1900._5.scm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScmMessages }
     * 
     */
    public ScmMessages createScmMessages() {
        return new ScmMessages();
    }

    /**
     * Create an instance of {@link TxModel }
     * 
     */
    public TxModel createTxModel() {
        return new TxModel();
    }

    /**
     * Create an instance of {@link RxModel }
     * 
     */
    public RxModel createRxModel() {
        return new RxModel();
    }

    /**
     * Create an instance of {@link SystemModel }
     * 
     */
    public SystemModel createSystemModel() {
        return new SystemModel();
    }

    /**
     * Create an instance of {@link SCMSet }
     * 
     */
    public SCMSet createSCMSet() {
        return new SCMSet();
    }

    /**
     * Create an instance of {@link Confidence }
     * 
     */
    public Confidence createConfidence() {
        return new Confidence();
    }

    /**
     * Create an instance of {@link SpectrumMask }
     * 
     */
    public SpectrumMask createSpectrumMask() {
        return new SpectrumMask();
    }

    /**
     * Create an instance of {@link HopRated }
     * 
     */
    public HopRated createHopRated() {
        return new HopRated();
    }

    /**
     * Create an instance of {@link SCMLocation }
     * 
     */
    public SCMLocation createSCMLocation() {
        return new SCMLocation();
    }

    /**
     * Create an instance of {@link SCMPolicyOrProtocol }
     * 
     */
    public SCMPolicyOrProtocol createSCMPolicyOrProtocol() {
        return new SCMPolicyOrProtocol();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link FrequencyList }
     * 
     */
    public FrequencyList createFrequencyList() {
        return new FrequencyList();
    }

    /**
     * Create an instance of {@link Discrete }
     * 
     */
    public Discrete createDiscrete() {
        return new Discrete();
    }

    /**
     * Create an instance of {@link XcvrModel }
     * 
     */
    public XcvrModel createXcvrModel() {
        return new XcvrModel();
    }

    /**
     * Create an instance of {@link Tunability }
     * 
     */
    public Tunability createTunability() {
        return new Tunability();
    }

    /**
     * Create an instance of {@link PolygonSurface }
     * 
     */
    public PolygonSurface createPolygonSurface() {
        return new PolygonSurface();
    }

    /**
     * Create an instance of {@link Side }
     * 
     */
    public Side createSide() {
        return new Side();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link HoppingData }
     * 
     */
    public HoppingData createHoppingData() {
        return new HoppingData();
    }

    /**
     * Create an instance of {@link PolarizationGain }
     * 
     */
    public PolarizationGain createPolarizationGain() {
        return new PolarizationGain();
    }

    /**
     * Create an instance of {@link DCRating }
     * 
     */
    public DCRating createDCRating() {
        return new DCRating();
    }

    /**
     * Create an instance of {@link Continuous }
     * 
     */
    public Continuous createContinuous() {
        return new Continuous();
    }

    /**
     * Create an instance of {@link IntermodulationMask }
     * 
     */
    public IntermodulationMask createIntermodulationMask() {
        return new IntermodulationMask();
    }

    /**
     * Create an instance of {@link Incremental }
     * 
     */
    public Incremental createIncremental() {
        return new Incremental();
    }

    /**
     * Create an instance of {@link PropagationModel }
     * 
     */
    public PropagationModel createPropagationModel() {
        return new PropagationModel();
    }

    /**
     * Create an instance of {@link PiecewiseLogLinear }
     * 
     */
    public PiecewiseLogLinear createPiecewiseLogLinear() {
        return new PiecewiseLogLinear();
    }

    /**
     * Create an instance of {@link UnderlayMask }
     * 
     */
    public UnderlayMask createUnderlayMask() {
        return new UnderlayMask();
    }

    /**
     * Create an instance of {@link UberModel }
     * 
     */
    public UberModel createUberModel() {
        return new UberModel();
    }

    /**
     * Create an instance of {@link CircularSurface }
     * 
     */
    public CircularSurface createCircularSurface() {
        return new CircularSurface();
    }

    /**
     * Create an instance of {@link SCMMask }
     * 
     */
    public SCMMask createSCMMask() {
        return new SCMMask();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link Cycle }
     * 
     */
    public Cycle createCycle() {
        return new Cycle();
    }

    /**
     * Create an instance of {@link ReferencePower }
     * 
     */
    public ReferencePower createReferencePower() {
        return new ReferencePower();
    }

    /**
     * Create an instance of {@link BandList }
     * 
     */
    public BandList createBandList() {
        return new BandList();
    }

    /**
     * Create an instance of {@link Polyhedron }
     * 
     */
    public Polyhedron createPolyhedron() {
        return new Polyhedron();
    }

    /**
     * Create an instance of {@link GainMapValue }
     * 
     */
    public GainMapValue createGainMapValue() {
        return new GainMapValue();
    }

    /**
     * Create an instance of {@link Multiple }
     * 
     */
    public Multiple createMultiple() {
        return new Multiple();
    }

    /**
     * Create an instance of {@link RelativeToPlatform }
     * 
     */
    public RelativeToPlatform createRelativeToPlatform() {
        return new RelativeToPlatform();
    }

    /**
     * Create an instance of {@link SCMSchedule }
     * 
     */
    public SCMSchedule createSCMSchedule() {
        return new SCMSchedule();
    }

    /**
     * Create an instance of {@link PropMap }
     * 
     */
    public PropMap createPropMap() {
        return new PropMap();
    }

    /**
     * Create an instance of {@link PorPParameters }
     * 
     */
    public PorPParameters createPorPParameters() {
        return new PorPParameters();
    }

    /**
     * Create an instance of {@link Pair }
     * 
     */
    public Pair createPair() {
        return new Pair();
    }

    /**
     * Create an instance of {@link SCMPlatform }
     * 
     */
    public SCMPlatform createSCMPlatform() {
        return new SCMPlatform();
    }

    /**
     * Create an instance of {@link Cylinder }
     * 
     */
    public Cylinder createCylinder() {
        return new Cylinder();
    }

    /**
     * Create an instance of {@link AntennaHeight }
     * 
     */
    public AntennaHeight createAntennaHeight() {
        return new AntennaHeight();
    }

    /**
     * Create an instance of {@link LogLinearValue }
     * 
     */
    public LogLinearValue createLogLinearValue() {
        return new LogLinearValue();
    }

    /**
     * Create an instance of {@link SCMPolygon }
     * 
     */
    public SCMPolygon createSCMPolygon() {
        return new SCMPolygon();
    }

    /**
     * Create an instance of {@link SCMPropagationMap }
     * 
     */
    public SCMPropagationMap createSCMPropagationMap() {
        return new SCMPropagationMap();
    }

    /**
     * Create an instance of {@link ScanValue }
     * 
     */
    public ScanValue createScanValue() {
        return new ScanValue();
    }

    /**
     * Create an instance of {@link Alternatives }
     * 
     */
    public Alternatives createAlternatives() {
        return new Alternatives();
    }

    /**
     * Create an instance of {@link BTPRating }
     * 
     */
    public BTPRating createBTPRating() {
        return new BTPRating();
    }

    /**
     * Create an instance of {@link BTPRatedList }
     * 
     */
    public BTPRatedList createBTPRatedList() {
        return new BTPRatedList();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link BWRatedList }
     * 
     */
    public BWRatedList createBWRatedList() {
        return new BWRatedList();
    }

    /**
     * Create an instance of {@link SCMPowerMap }
     * 
     */
    public SCMPowerMap createSCMPowerMap() {
        return new SCMPowerMap();
    }

    /**
     * Create an instance of {@link Orientation }
     * 
     */
    public Orientation createOrientation() {
        return new Orientation();
    }

    /**
     * Create an instance of {@link LinearLossValue }
     * 
     */
    public LinearLossValue createLinearLossValue() {
        return new LinearLossValue();
    }

    /**
     * Create an instance of {@link ControlPoint }
     * 
     */
    public ControlPoint createControlPoint() {
        return new ControlPoint();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link GainMap }
     * 
     */
    public GainMap createGainMap() {
        return new GainMap();
    }

    /**
     * Create an instance of {@link PointSurface }
     * 
     */
    public PointSurface createPointSurface() {
        return new PointSurface();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link BWRating }
     * 
     */
    public BWRating createBWRating() {
        return new BWRating();
    }

    /**
     * Create an instance of {@link Band }
     * 
     */
    public Band createBand() {
        return new Band();
    }

    /**
     * Create an instance of {@link DCRatedList }
     * 
     */
    public DCRatedList createDCRatedList() {
        return new DCRatedList();
    }

    /**
     * Create an instance of {@link LinearLosses }
     * 
     */
    public LinearLosses createLinearLosses() {
        return new LinearLosses();
    }

    /**
     * Create an instance of {@link PathPoint }
     * 
     */
    public PathPoint createPathPoint() {
        return new PathPoint();
    }

    /**
     * Create an instance of {@link Combinations }
     * 
     */
    public Combinations createCombinations() {
        return new Combinations();
    }

    /**
     * Create an instance of {@link TowardReferencePoint }
     * 
     */
    public TowardReferencePoint createTowardReferencePoint() {
        return new TowardReferencePoint();
    }

    /**
     * Create an instance of {@link Boundary }
     * 
     */
    public Boundary createBoundary() {
        return new Boundary();
    }

    /**
     * Create an instance of {@link ScanningRegion }
     * 
     */
    public ScanningRegion createScanningRegion() {
        return new ScanningRegion();
    }

    /**
     * Create an instance of {@link Competing }
     * 
     */
    public Competing createCompeting() {
        return new Competing();
    }

    /**
     * Create an instance of {@link SurfacePath }
     * 
     */
    public SurfacePath createSurfacePath() {
        return new SurfacePath();
    }

    /**
     * Create an instance of {@link PropMapValue }
     * 
     */
    public PropMapValue createPropMapValue() {
        return new PropMapValue();
    }

}
