//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Options complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Options">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xcvrModel" type="{}XcvrModel" maxOccurs="unbounded"/>
 *         &lt;element name="combinations" type="{}Combinations" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Options", propOrder = {
    "xcvrModel",
    "combinations"
})
public class Options {

    @XmlElement(required = true)
    protected List<XcvrModel> xcvrModel;
    protected Combinations combinations;

    /**
     * Gets the value of the xcvrModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xcvrModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXcvrModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XcvrModel }
     * 
     * 
     */
    public List<XcvrModel> getXcvrModel() {
        if (xcvrModel == null) {
            xcvrModel = new ArrayList<XcvrModel>();
        }
        return this.xcvrModel;
    }

    /**
     * Gets the value of the combinations property.
     * 
     * @return
     *     possible object is
     *     {@link Combinations }
     *     
     */
    public Combinations getCombinations() {
        return combinations;
    }

    /**
     * Sets the value of the combinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Combinations }
     *     
     */
    public void setCombinations(Combinations value) {
        this.combinations = value;
    }

}
