//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Orientation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Orientation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="surface" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *           &lt;element name="relativeToPlatform" type="{}RelativeToPlatform"/>
 *           &lt;element name="towardReferencePoint" type="{}TowardReferencePoint"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Orientation", propOrder = {
    "surface",
    "relativeToPlatform",
    "towardReferencePoint"
})
public class Orientation {

    protected Boolean surface;
    protected RelativeToPlatform relativeToPlatform;
    protected TowardReferencePoint towardReferencePoint;

    /**
     * Gets the value of the surface property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSurface() {
        return surface;
    }

    /**
     * Sets the value of the surface property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSurface(Boolean value) {
        this.surface = value;
    }

    /**
     * Gets the value of the relativeToPlatform property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeToPlatform }
     *     
     */
    public RelativeToPlatform getRelativeToPlatform() {
        return relativeToPlatform;
    }

    /**
     * Sets the value of the relativeToPlatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeToPlatform }
     *     
     */
    public void setRelativeToPlatform(RelativeToPlatform value) {
        this.relativeToPlatform = value;
    }

    /**
     * Gets the value of the towardReferencePoint property.
     * 
     * @return
     *     possible object is
     *     {@link TowardReferencePoint }
     *     
     */
    public TowardReferencePoint getTowardReferencePoint() {
        return towardReferencePoint;
    }

    /**
     * Sets the value of the towardReferencePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link TowardReferencePoint }
     *     
     */
    public void setTowardReferencePoint(TowardReferencePoint value) {
        this.towardReferencePoint = value;
    }

}
