//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Polyhedron complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Polyhedron">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scmPolygon" type="{}SCMPolygon"/>
 *         &lt;element name="height" type="{}positive-double"/>
 *         &lt;element name="transmitterDensity" type="{}positive-double" minOccurs="0"/>
 *         &lt;element name="topAttenuation" type="{}non-negative-double" minOccurs="0"/>
 *         &lt;element name="bottomAttenuation" type="{}non-negative-double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Polyhedron", propOrder = {
    "scmPolygon",
    "height",
    "transmitterDensity",
    "topAttenuation",
    "bottomAttenuation"
})
public class Polyhedron {

    @XmlElement(required = true)
    protected SCMPolygon scmPolygon;
    protected double height;
    protected Double transmitterDensity;
    protected Double topAttenuation;
    protected Double bottomAttenuation;

    /**
     * Gets the value of the scmPolygon property.
     * 
     * @return
     *     possible object is
     *     {@link SCMPolygon }
     *     
     */
    public SCMPolygon getScmPolygon() {
        return scmPolygon;
    }

    /**
     * Sets the value of the scmPolygon property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCMPolygon }
     *     
     */
    public void setScmPolygon(SCMPolygon value) {
        this.scmPolygon = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(double value) {
        this.height = value;
    }

    /**
     * Gets the value of the transmitterDensity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTransmitterDensity() {
        return transmitterDensity;
    }

    /**
     * Sets the value of the transmitterDensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTransmitterDensity(Double value) {
        this.transmitterDensity = value;
    }

    /**
     * Gets the value of the topAttenuation property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTopAttenuation() {
        return topAttenuation;
    }

    /**
     * Sets the value of the topAttenuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTopAttenuation(Double value) {
        this.topAttenuation = value;
    }

    /**
     * Gets the value of the bottomAttenuation property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBottomAttenuation() {
        return bottomAttenuation;
    }

    /**
     * Sets the value of the bottomAttenuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBottomAttenuation(Double value) {
        this.bottomAttenuation = value;
    }

}
