//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropagationModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropagationModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="piecewiseLogLinear" type="{}PiecewiseLogLinear"/>
 *         &lt;element name="linearLosses" type="{}LinearLosses" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropagationModel", propOrder = {
    "piecewiseLogLinear",
    "linearLosses"
})
public class PropagationModel {

    @XmlElement(required = true)
    protected PiecewiseLogLinear piecewiseLogLinear;
    protected LinearLosses linearLosses;

    /**
     * Gets the value of the piecewiseLogLinear property.
     * 
     * @return
     *     possible object is
     *     {@link PiecewiseLogLinear }
     *     
     */
    public PiecewiseLogLinear getPiecewiseLogLinear() {
        return piecewiseLogLinear;
    }

    /**
     * Sets the value of the piecewiseLogLinear property.
     * 
     * @param value
     *     allowed object is
     *     {@link PiecewiseLogLinear }
     *     
     */
    public void setPiecewiseLogLinear(PiecewiseLogLinear value) {
        this.piecewiseLogLinear = value;
    }

    /**
     * Gets the value of the linearLosses property.
     * 
     * @return
     *     possible object is
     *     {@link LinearLosses }
     *     
     */
    public LinearLosses getLinearLosses() {
        return linearLosses;
    }

    /**
     * Sets the value of the linearLosses property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinearLosses }
     *     
     */
    public void setLinearLosses(LinearLosses value) {
        this.linearLosses = value;
    }

}
