/*
Copyright (C) 2016 Syracuse University

This file is part of the Spectrum Consumption Model Builder and
Analysis Tool

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with program.  If not, see <http://www.gnu.org/licenses/>.

*/

/*
This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
Any modifications to this file will be lost upon recompilation of the source schema. 
*/

package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ratedBW" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bwRatedList" type="{http://www.ieee.org/DyspanSC/1900/5/SCM}BWRatedListType"/>
 *         &lt;element name="ratedBTP" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="btpRatedList" type="{http://www.ieee.org/DyspanSC/1900/5/SCM}BTPRatedListType"/>
 *         &lt;element name="dcRatedList" type="{http://www.ieee.org/DyspanSC/1900/5/SCM}DCRatedListType"/>
 *         &lt;element name="porpIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatingType", propOrder = {
    "ratedBW",
    "bwRatedList",
    "ratedBTP",
    "btpRatedList",
    "dcRatedList",
    "porpIndex"
})
public class RatingType {

    protected double ratedBW;
    @XmlElement(required = true)
    protected BWRatedListType bwRatedList;
    protected double ratedBTP;
    @XmlElement(required = true)
    protected BTPRatedListType btpRatedList;
    @XmlElement(required = true)
    protected DCRatedListType dcRatedList;
    protected int porpIndex;

    /**
     * Gets the value of the ratedBW property.
     * 
     */
    public double getRatedBW() {
        return ratedBW;
    }

    /**
     * Sets the value of the ratedBW property.
     * 
     */
    public void setRatedBW(double value) {
        this.ratedBW = value;
    }

    /**
     * Gets the value of the bwRatedList property.
     * 
     * @return
     *     possible object is
     *     {@link BWRatedListType }
     *     
     */
    public BWRatedListType getBwRatedList() {
        return bwRatedList;
    }

    /**
     * Sets the value of the bwRatedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BWRatedListType }
     *     
     */
    public void setBwRatedList(BWRatedListType value) {
        this.bwRatedList = value;
    }

    /**
     * Gets the value of the ratedBTP property.
     * 
     */
    public double getRatedBTP() {
        return ratedBTP;
    }

    /**
     * Sets the value of the ratedBTP property.
     * 
     */
    public void setRatedBTP(double value) {
        this.ratedBTP = value;
    }

    /**
     * Gets the value of the btpRatedList property.
     * 
     * @return
     *     possible object is
     *     {@link BTPRatedListType }
     *     
     */
    public BTPRatedListType getBtpRatedList() {
        return btpRatedList;
    }

    /**
     * Sets the value of the btpRatedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BTPRatedListType }
     *     
     */
    public void setBtpRatedList(BTPRatedListType value) {
        this.btpRatedList = value;
    }

    /**
     * Gets the value of the dcRatedList property.
     * 
     * @return
     *     possible object is
     *     {@link DCRatedListType }
     *     
     */
    public DCRatedListType getDcRatedList() {
        return dcRatedList;
    }

    /**
     * Sets the value of the dcRatedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DCRatedListType }
     *     
     */
    public void setDcRatedList(DCRatedListType value) {
        this.dcRatedList = value;
    }

    /**
     * Gets the value of the porpIndex property.
     * 
     */
    public int getPorpIndex() {
        return porpIndex;
    }

    /**
     * Sets the value of the porpIndex property.
     * 
     */
    public void setPorpIndex(int value) {
        this.porpIndex = value;
    }

}
