//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelativeToPlatform complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelativeToPlatform">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zRotation" type="{}double-angle"/>
 *         &lt;element name="yRotation" type="{}double-angle"/>
 *         &lt;element name="xRotation" type="{}double-angle"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelativeToPlatform", propOrder = {
    "zRotation",
    "yRotation",
    "xRotation"
})
public class RelativeToPlatform {

    protected double zRotation;
    protected double yRotation;
    protected double xRotation;

    /**
     * Gets the value of the zRotation property.
     * 
     */
    public double getZRotation() {
        return zRotation;
    }

    /**
     * Sets the value of the zRotation property.
     * 
     */
    public void setZRotation(double value) {
        this.zRotation = value;
    }

    /**
     * Gets the value of the yRotation property.
     * 
     */
    public double getYRotation() {
        return yRotation;
    }

    /**
     * Sets the value of the yRotation property.
     * 
     */
    public void setYRotation(double value) {
        this.yRotation = value;
    }

    /**
     * Gets the value of the xRotation property.
     * 
     */
    public double getXRotation() {
        return xRotation;
    }

    /**
     * Sets the value of the xRotation property.
     * 
     */
    public void setXRotation(double value) {
        this.xRotation = value;
    }

}
