//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SCMMask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SCMMask">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refFrequency" type="{}positive-double"/>
 *         &lt;element name="controlPoint" type="{}ControlPoint" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SCMMask", propOrder = {
    "refFrequency",
    "controlPoint"
})
public class SCMMask {

    protected Double refFrequency;
    @XmlElement(required = true)
    protected List<ControlPoint> controlPoint;

    /**
     * Gets the value of the refFrequency property.
     * 
     */
    public Double getRefFrequency() {
        return refFrequency;
    }

    /**
     * Sets the value of the refFrequency property.
     * 
     */
    public void setRefFrequency(Double value) {
        this.refFrequency = value;
    }

    /**
     * Gets the value of the controlPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControlPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlPoint }
     * 
     * 
     */
    public List<ControlPoint> getControlPoint() {
        if (controlPoint == null) {
            controlPoint = new ArrayList<ControlPoint>();
        }
        return this.controlPoint;
    }

}
