//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="txModel" type="{}TxModel" minOccurs="0"/>
 *         &lt;element name="rxModel" type="{}RxModel" minOccurs="0"/>
 *         &lt;element name="systemModel" type="{}SystemModel" minOccurs="0"/>
 *         &lt;element name="scmSet" type="{}SCMSet" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "txModel",
    "rxModel",
    "systemModel",
    "scmSet"
})
@XmlRootElement(name = "scmMessages")
public class ScmMessages {

    protected TxModel txModel;
    protected RxModel rxModel;
    protected SystemModel systemModel;
    protected SCMSet scmSet;

    /**
     * Gets the value of the txModel property.
     * 
     * @return
     *     possible object is
     *     {@link TxModel }
     *     
     */
    public TxModel getTxModel() {
        return txModel;
    }

    /**
     * Sets the value of the txModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxModel }
     *     
     */
    public void setTxModel(TxModel value) {
        this.txModel = value;
    }

    /**
     * Gets the value of the rxModel property.
     * 
     * @return
     *     possible object is
     *     {@link RxModel }
     *     
     */
    public RxModel getRxModel() {
        return rxModel;
    }

    /**
     * Sets the value of the rxModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxModel }
     *     
     */
    public void setRxModel(RxModel value) {
        this.rxModel = value;
    }

    /**
     * Gets the value of the systemModel property.
     * 
     * @return
     *     possible object is
     *     {@link SystemModel }
     *     
     */
    public SystemModel getSystemModel() {
        return systemModel;
    }

    /**
     * Sets the value of the systemModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemModel }
     *     
     */
    public void setSystemModel(SystemModel value) {
        this.systemModel = value;
    }

    /**
     * Gets the value of the scmSet property.
     * 
     * @return
     *     possible object is
     *     {@link SCMSet }
     *     
     */
    public SCMSet getScmSet() {
        return scmSet;
    }

    /**
     * Sets the value of the scmSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCMSet }
     *     
     */
    public void setScmSet(SCMSet value) {
        this.scmSet = value;
    }

}
