//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SCMPolicyOrProtocol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SCMPolicyOrProtocol">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="porPName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="porPParameters" type="{}PorPParameters" minOccurs="0"/>
 *         &lt;element name="porPIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SCMPolicyOrProtocol", propOrder = {
    "porPName",
    "porPParameters",
    "porPIndex"
})
public class SCMPolicyOrProtocol {

    @XmlElement(required = true)
    protected String porPName;
    protected PorPParameters porPParameters;
    protected Integer porPIndex;

    /**
     * Gets the value of the porPName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPorPName() {
        return porPName;
    }

    /**
     * Sets the value of the porPName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPorPName(String value) {
        this.porPName = value;
    }

    /**
     * Gets the value of the porPParameters property.
     * 
     * @return
     *     possible object is
     *     {@link PorPParameters }
     *     
     */
    public PorPParameters getPorPParameters() {
        return porPParameters;
    }

    /**
     * Sets the value of the porPParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link PorPParameters }
     *     
     */
    public void setPorPParameters(PorPParameters value) {
        this.porPParameters = value;
    }

    /**
     * Gets the value of the porPIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPorPIndex() {
        return porPIndex;
    }

    /**
     * Sets the value of the porPIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPorPIndex(Integer value) {
        this.porPIndex = value;
    }

}
