//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SCMPowerMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SCMPowerMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orientation" type="{}Orientation"/>
 *         &lt;element name="scanningRegion" type="{}ScanningRegion" minOccurs="0"/>
 *         &lt;element name="gainMap" type="{}GainMap"/>
 *         &lt;element name="polarizationGain" type="{}PolarizationGain" maxOccurs="4" minOccurs="0"/>
 *         &lt;element name="locationIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="confidence" type="{}Confidence" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SCMPowerMap", propOrder = {
    "orientation",
    "scanningRegion",
    "gainMap",
    "polarizationGain",
    "locationIndex",
    "confidence"
})
public class SCMPowerMap {

    @XmlElement(required = true)
    protected Orientation orientation;
    protected ScanningRegion scanningRegion;
    @XmlElement(required = true)
    protected GainMap gainMap;
    protected List<PolarizationGain> polarizationGain;
    protected Integer locationIndex;
    protected Confidence confidence;

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link Orientation }
     *     
     */
    public Orientation getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orientation }
     *     
     */
    public void setOrientation(Orientation value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the scanningRegion property.
     * 
     * @return
     *     possible object is
     *     {@link ScanningRegion }
     *     
     */
    public ScanningRegion getScanningRegion() {
        return scanningRegion;
    }

    /**
     * Sets the value of the scanningRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanningRegion }
     *     
     */
    public void setScanningRegion(ScanningRegion value) {
        this.scanningRegion = value;
    }

    /**
     * Gets the value of the gainMap property.
     * 
     * @return
     *     possible object is
     *     {@link GainMap }
     *     
     */
    public GainMap getGainMap() {
        return gainMap;
    }

    /**
     * Sets the value of the gainMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link GainMap }
     *     
     */
    public void setGainMap(GainMap value) {
        this.gainMap = value;
    }

    /**
     * Gets the value of the polarizationGain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the polarizationGain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolarizationGain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolarizationGain }
     * 
     * 
     */
    public List<PolarizationGain> getPolarizationGain() {
        if (polarizationGain == null) {
            polarizationGain = new ArrayList<PolarizationGain>();
        }
        return this.polarizationGain;
    }

    /**
     * Gets the value of the locationIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLocationIndex() {
        return locationIndex;
    }

    /**
     * Sets the value of the locationIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLocationIndex(Integer value) {
        this.locationIndex = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Confidence }
     *     
     */
    public Confidence getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Confidence }
     *     
     */
    public void setConfidence(Confidence value) {
        this.confidence = value;
    }

}
