//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tunability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tunability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="continuous" type="{}Continuous" maxOccurs="unbounded"/>
 *           &lt;element name="incremental" type="{}Incremental" maxOccurs="unbounded"/>
 *           &lt;element name="discrete" type="{}Discrete" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element name="txModel" type="{}TxModel" minOccurs="0"/>
 *         &lt;element name="rxModel" type="{}RxModel" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tunability", propOrder = {
    "continuous",
    "incremental",
    "discrete",
    "txModel",
    "rxModel"
})
public class Tunability {

    protected List<Continuous> continuous;
    protected List<Incremental> incremental;
    protected List<Discrete> discrete;
    protected TxModel txModel;
    protected RxModel rxModel;

    /**
     * Gets the value of the continuous property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the continuous property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContinuous().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Continuous }
     * 
     * 
     */
    public List<Continuous> getContinuous() {
        if (continuous == null) {
            continuous = new ArrayList<Continuous>();
        }
        return this.continuous;
    }

    /**
     * Gets the value of the incremental property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incremental property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncremental().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Incremental }
     * 
     * 
     */
    public List<Incremental> getIncremental() {
        if (incremental == null) {
            incremental = new ArrayList<Incremental>();
        }
        return this.incremental;
    }

    /**
     * Gets the value of the discrete property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discrete property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscrete().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Discrete }
     * 
     * 
     */
    public List<Discrete> getDiscrete() {
        if (discrete == null) {
            discrete = new ArrayList<Discrete>();
        }
        return this.discrete;
    }

    /**
     * Gets the value of the txModel property.
     * 
     * @return
     *     possible object is
     *     {@link TxModel }
     *     
     */
    public TxModel getTxModel() {
        return txModel;
    }

    /**
     * Sets the value of the txModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxModel }
     *     
     */
    public void setTxModel(TxModel value) {
        this.txModel = value;
    }

    /**
     * Gets the value of the rxModel property.
     * 
     * @return
     *     possible object is
     *     {@link RxModel }
     *     
     */
    public RxModel getRxModel() {
        return rxModel;
    }

    /**
     * Sets the value of the rxModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxModel }
     *     
     */
    public void setRxModel(RxModel value) {
        this.rxModel = value;
    }

}
