//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TxModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TxModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="systemID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xcvrName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deviceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="purpose" type="{}Purpose"/>
 *         &lt;element name="confidence" type="{}Confidence" minOccurs="0"/>
 *         &lt;element name="referencePower" type="{}ReferencePower" maxOccurs="unbounded"/>
 *         &lt;element name="spectrumMask" type="{}SpectrumMask" maxOccurs="unbounded"/>
 *         &lt;element name="underlayMask" type="{}UnderlayMask" minOccurs="0"/>
 *         &lt;element name="scmPowerMap" type="{}SCMPowerMap" maxOccurs="unbounded"/>
 *         &lt;element name="scmPropagationMap" type="{}SCMPropagationMap" maxOccurs="unbounded"/>
 *         &lt;element name="intermodulationMask" type="{}IntermodulationMask" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="scmPlatform" type="{}SCMPlatform" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="scmLocation" type="{}SCMLocation" maxOccurs="unbounded"/>
 *         &lt;element name="scmSchedule" type="{}SCMSchedule" maxOccurs="unbounded"/>
 *         &lt;element name="minimumPowerSpectralFluxDensity" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="scmPolicyOrProtocol" type="{}SCMPolicyOrProtocol" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TxModel", propOrder = {
    "systemID",
    "xcvrName",
    "deviceID",
    "purpose",
    "confidence",
    "referencePower",
    "spectrumMask",
    "underlayMask",
    "scmPowerMap",
    "scmPropagationMap",
    "intermodulationMask",
    "scmPlatform",
    "scmLocation",
    "scmSchedule",
    "minimumPowerSpectralFluxDensity",
    "scmPolicyOrProtocol"
})
public class TxModel {

    protected String systemID;
    protected String xcvrName;
    protected String deviceID;
    @XmlElement(required = true)
    protected Purpose purpose;
    protected Confidence confidence;
    @XmlElement(required = true)
    protected List<ReferencePower> referencePower;
    @XmlElement(required = true)
    protected List<SpectrumMask> spectrumMask;
    protected UnderlayMask underlayMask;
    @XmlElement(required = true)
    protected List<SCMPowerMap> scmPowerMap;
    @XmlElement(required = true)
    protected List<SCMPropagationMap> scmPropagationMap;
    @XmlElement(nillable = true)
    protected List<IntermodulationMask> intermodulationMask;
    @XmlElement(nillable = true)
    protected List<SCMPlatform> scmPlatform;
    @XmlElement(required = true)
    protected List<SCMLocation> scmLocation;
    @XmlElement(required = true)
    protected List<SCMSchedule> scmSchedule;
    protected Double minimumPowerSpectralFluxDensity;
    protected SCMPolicyOrProtocol scmPolicyOrProtocol;

    /**
     * Gets the value of the systemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemID() {
        return systemID;
    }

    /**
     * Sets the value of the systemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemID(String value) {
        this.systemID = value;
    }

    /**
     * Gets the value of the xcvrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXcvrName() {
        return xcvrName;
    }

    /**
     * Sets the value of the xcvrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXcvrName(String value) {
        this.xcvrName = value;
    }

    /**
     * Gets the value of the deviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceID() {
        return deviceID;
    }

    /**
     * Sets the value of the deviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceID(String value) {
        this.deviceID = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link Purpose }
     *     
     */
    public Purpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purpose }
     *     
     */
    public void setPurpose(Purpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Confidence }
     *     
     */
    public Confidence getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Confidence }
     *     
     */
    public void setConfidence(Confidence value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the referencePower property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencePower property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferencePower().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferencePower }
     * 
     * 
     */
    public List<ReferencePower> getReferencePower() {
        if (referencePower == null) {
            referencePower = new ArrayList<ReferencePower>();
        }
        return this.referencePower;
    }

    /**
     * Gets the value of the spectrumMask property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spectrumMask property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpectrumMask().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpectrumMask }
     * 
     * 
     */
    public List<SpectrumMask> getSpectrumMask() {
        if (spectrumMask == null) {
            spectrumMask = new ArrayList<SpectrumMask>();
        }
        return this.spectrumMask;
    }

    /**
     * Gets the value of the underlayMask property.
     * 
     * @return
     *     possible object is
     *     {@link UnderlayMask }
     *     
     */
    public UnderlayMask getUnderlayMask() {
        return underlayMask;
    }

    /**
     * Sets the value of the underlayMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderlayMask }
     *     
     */
    public void setUnderlayMask(UnderlayMask value) {
        this.underlayMask = value;
    }

    /**
     * Gets the value of the scmPowerMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scmPowerMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScmPowerMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SCMPowerMap }
     * 
     * 
     */
    public List<SCMPowerMap> getScmPowerMap() {
        if (scmPowerMap == null) {
            scmPowerMap = new ArrayList<SCMPowerMap>();
        }
        return this.scmPowerMap;
    }

    /**
     * Gets the value of the scmPropagationMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scmPropagationMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScmPropagationMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SCMPropagationMap }
     * 
     * 
     */
    public List<SCMPropagationMap> getScmPropagationMap() {
        if (scmPropagationMap == null) {
            scmPropagationMap = new ArrayList<SCMPropagationMap>();
        }
        return this.scmPropagationMap;
    }

    /**
     * Gets the value of the intermodulationMask property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intermodulationMask property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntermodulationMask().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IntermodulationMask }
     * 
     * 
     */
    public List<IntermodulationMask> getIntermodulationMask() {
        if (intermodulationMask == null) {
            intermodulationMask = new ArrayList<IntermodulationMask>();
        }
        return this.intermodulationMask;
    }

    /**
     * Gets the value of the scmPlatform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scmPlatform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScmPlatform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SCMPlatform }
     * 
     * 
     */
    public List<SCMPlatform> getScmPlatform() {
        if (scmPlatform == null) {
            scmPlatform = new ArrayList<SCMPlatform>();
        }
        return this.scmPlatform;
    }

    /**
     * Gets the value of the scmLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scmLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScmLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SCMLocation }
     * 
     * 
     */
    public List<SCMLocation> getScmLocation() {
        if (scmLocation == null) {
            scmLocation = new ArrayList<SCMLocation>();
        }
        return this.scmLocation;
    }

    /**
     * Gets the value of the scmSchedule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scmSchedule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScmSchedule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SCMSchedule }
     * 
     * 
     */
    public List<SCMSchedule> getScmSchedule() {
        if (scmSchedule == null) {
            scmSchedule = new ArrayList<SCMSchedule>();
        }
        return this.scmSchedule;
    }

    /**
     * Gets the value of the minimumPowerSpectralFluxDensity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinimumPowerSpectralFluxDensity() {
        return minimumPowerSpectralFluxDensity;
    }

    /**
     * Sets the value of the minimumPowerSpectralFluxDensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinimumPowerSpectralFluxDensity(Double value) {
        this.minimumPowerSpectralFluxDensity = value;
    }

    /**
     * Gets the value of the scmPolicyOrProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link SCMPolicyOrProtocol }
     *     
     */
    public SCMPolicyOrProtocol getScmPolicyOrProtocol() {
        return scmPolicyOrProtocol;
    }

    /**
     * Sets the value of the scmPolicyOrProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCMPolicyOrProtocol }
     *     
     */
    public void setScmPolicyOrProtocol(SCMPolicyOrProtocol value) {
        this.scmPolicyOrProtocol = value;
    }

}
