//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 01:08:10 PM IST 
//


package org.ieee.dyspansc._1900._5.scm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnderlayMask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnderlayMask">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rating" type="{}Rating" minOccurs="0"/>
 *         &lt;element name="resolutionBW" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="scmMask" type="{}SCMMask"/>
 *         &lt;element name="maskPowerMarginMethod" type="{}MaskPowerMarginMethod"/>
 *         &lt;element name="confidence" type="{}Confidence" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnderlayMask", propOrder = {
    "rating",
    "resolutionBW",
    "scmMask",
    "maskPowerMarginMethod",
    "confidence"
})
public class UnderlayMask {

    protected Rating rating;
    protected double resolutionBW;
    @XmlElement(required = true)
    protected SCMMask scmMask;
    @XmlElement(required = true)
    protected MaskPowerMarginMethod maskPowerMarginMethod;
    protected Confidence confidence;

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link Rating }
     *     
     */
    public Rating getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rating }
     *     
     */
    public void setRating(Rating value) {
        this.rating = value;
    }

    /**
     * Gets the value of the resolutionBW property.
     * 
     */
    public double getResolutionBW() {
        return resolutionBW;
    }

    /**
     * Sets the value of the resolutionBW property.
     * 
     */
    public void setResolutionBW(double value) {
        this.resolutionBW = value;
    }

    /**
     * Gets the value of the scmMask property.
     * 
     * @return
     *     possible object is
     *     {@link SCMMask }
     *     
     */
    public SCMMask getScmMask() {
        return scmMask;
    }

    /**
     * Sets the value of the scmMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCMMask }
     *     
     */
    public void setScmMask(SCMMask value) {
        this.scmMask = value;
    }

    /**
     * Gets the value of the maskPowerMarginMethod property.
     * 
     * @return
     *     possible object is
     *     {@link MaskPowerMarginMethod }
     *     
     */
    public MaskPowerMarginMethod getMaskPowerMarginMethod() {
        return maskPowerMarginMethod;
    }

    /**
     * Sets the value of the maskPowerMarginMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaskPowerMarginMethod }
     *     
     */
    public void setMaskPowerMarginMethod(MaskPowerMarginMethod value) {
        this.maskPowerMarginMethod = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Confidence }
     *     
     */
    public Confidence getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Confidence }
     *     
     */
    public void setConfidence(Confidence value) {
        this.confidence = value;
    }

}
